### ISSUE TITLE
Can we not have UPPERCASE all over the vocabulary?

### ISSUE THREAD

**Issue by jenhsun** [badarsh2/Sudocabulary#2]
Thanks for your work. However, vocabulary all uppercase is difficult to read. Can you change that?

**Comment by jenhsun** [comment]
Ha, I end up fork it and lowercase myself. Problem solved.

**Comment by camilosampedro** [comment]
I second this request, even if it's marked as closed. It's difficult to read all uppercase.

By the way, thank you for the script, it's really interesting.
